"""
MIDAS YOLOv11 Training Pipeline.

Usage:
    python train.py                         # train with default config
    python train.py --config path/to.yaml   # train with custom config
    python train.py --resume                # resume from last checkpoint
"""

import os
import sys
import argparse

from ultralytics import YOLO

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from configs.config import load_config
from data.prepare_dataset import generate_dataset_yaml


def train(config_path: str = None, resume: bool = False):
    cfg = load_config(config_path)
    ml_root = os.path.dirname(os.path.abspath(__file__))

    # Use merged dataset.yaml (generated by data/merge_datasets.py)
    dataset_yaml_path = os.path.join(ml_root, cfg.data.dataset_yaml)
    if not os.path.exists(dataset_yaml_path):
        print(f"Dataset YAML not found at {dataset_yaml_path}")
        print("Run 'python data/merge_datasets.py' first to create the merged dataset.")
        sys.exit(1)

    # Load model
    if resume and os.path.exists(os.path.join(ml_root, cfg.data.checkpoint_dir, "train", "weights", "last.pt")):
        model_path = os.path.join(ml_root, cfg.data.checkpoint_dir, "train", "weights", "last.pt")
        print(f"Resuming from checkpoint: {model_path}")
        model = YOLO(model_path)
    else:
        # Load pretrained YOLOv11 variant
        model_name = cfg.model.variant + ".pt"
        print(f"Loading pretrained model: {model_name}")
        model = YOLO(model_name)

    # Train
    results = model.train(
        data=dataset_yaml_path,
        epochs=cfg.training.epochs,
        batch=cfg.training.batch_size,
        imgsz=cfg.model.image_size,
        lr0=cfg.training.learning_rate,
        optimizer=cfg.training.optimizer,
        patience=cfg.training.patience,
        device=cfg.training.device,
        workers=cfg.training.workers,
        augment=cfg.training.augment,
        seed=cfg.training.seed,
        project=os.path.join(ml_root, cfg.data.checkpoint_dir),
        name="train",
        exist_ok=True,
        verbose=True,
    )

    # Validate
    print("\nRunning validation...")
    metrics = model.val()
    print(f"mAP50:    {metrics.box.map50:.4f}")
    print(f"mAP50-95: {metrics.box.map:.4f}")

    # Export to ONNX for deployment
    best_path = os.path.join(ml_root, cfg.data.checkpoint_dir, "train", "weights", "best.pt")
    if os.path.exists(best_path):
        print("\nExporting best model to ONNX...")
        best_model = YOLO(best_path)
        best_model.export(format="onnx", imgsz=cfg.model.image_size)
        print("ONNX export complete.")

    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MIDAS YOLOv11 Training")
    parser.add_argument("--config", type=str, default=None, help="Path to config YAML")
    parser.add_argument("--resume", action="store_true", help="Resume from last checkpoint")
    args = parser.parse_args()

    train(config_path=args.config, resume=args.resume)
